### ISSUE TITLE
Occupancy Max Limit

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/spacey#10]
(i.e., have to fill out 25 people, classroom style - but if someone put in 50 people, classroom style for CR 3 - it wouldn’t allow them to book the room or something)

**Comment by tylercrosse** [comment]
PR submitted #26

**Comment by bmartinowich** [comment]
After submitted new event - it should create a conflict with max occupancy. Error message currently

**Comment by tylercrosse** [comment]
Now fixed with PR #29
