### ISSUE TITLE
Agenda Page Styling

### ISSUE THREAD

**Issue by JonRojas** [ga-dc/spacey#101]
I worked with Faz a bit on the agenda page styling.

**Requesting:**

Each event is a card. Card contains the subject logo, color to designate category, producer, instructors, notes, and classroom.

Cards are organized first by time (am to pm) and second by classroom (1-6, then by floor)

Mockup attached

![class card mockup](https://cloud.githubusercontent.com/assets/1315364/17342441/403e7ee6-58c7-11e6-98a6-e56b8a34d3fe.jpg)

**Comment by jshawl** [comment]
what do you think about this? 

![](https://dl.dropbox.com/s/baak7644mdrwexa/Screenshot%202016-08-02%2016.04.26.png?dl=0)

Logos are going to be tricky because some c &ws dont have logos

**Comment by JonRojas** [comment]
Perfect @jshawl. We can solve the logo issue in a future update (if ever!) 👨🏻

**Comment by bmartinowich** [comment]
@jshawl What are next steps here to create this layout? Let me know -- thanks!
