### ISSUE TITLE
Hover and clickable at a glance view don't work in firefox

### ISSUE THREAD

**Issue by laurencjay** [ga-dc/spacey#106]
As a dedicated mozilla user, I don't want to have to switch browsers to use spacey. (see screenshot) 

I can't click on any of these events or see the at a glance hover in this view. 

@bmartinowich 
![spacey 2016-08-31 13-22-39](https://cloud.githubusercontent.com/assets/8364411/18139121/035bcbdc-6f7e-11e6-9943-f81e84e20473.png)

**Comment by jshawl** [comment]
chrome > firefox
