### ISSUE TITLE
Hover feature for event details 

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/spacey#11]
When you hover over a booking, you can see all of the event details, including comments

**Comment by bmartinowich** [comment]
On hover - Start time, end time, name of class/event, room/space, producer, notes (# of notes?) instructor, number of attendees

**Comment by tylercrosse** [comment]
Check out PR
https://github.com/ga-dc/spacey/pull/21

**Comment by bmartinowich** [comment]
Awesome! thanks @tylercrosse
