### ISSUE TITLE
Security Certificate has expired 

### ISSUE THREAD

**Issue by laurencjay** [ga-dc/spacey#121]
@amaseda Could you get someone to take a look at this ASAP? It makes the page look like its insecure.

**Comment by amaseda** [comment]
@laurencjay Yup, talked about this with @JonRojas this morning! Can dive into this tomorrow after 10am. Unfortunately in the classroom until then.

**Comment by jshawl** [comment]
How to fix:

1: read https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates#renew-ssl-certificates

2. log into server : `ssh git@gadc.space`

3. become super user `su -`

4. run the commands in 1

5. reload nginx config:

```
sudo nginx -t
sudo service nginx reload
```

**Comment by JonRojas** [comment]
❤️  you @jshawl!

**Comment by JonRojas** [comment]
@jshawl do you have any idea what the superuser password is? 

(Don't answer on here, haha)

**Comment by JonRojas** [comment]
Certs have been renewed. Writing documentation and will post in wiki.
