### ISSUE TITLE
Month View and Year View

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/spacey#25]
Calendar format would probably make the most sense here, but open to other thoughts!

**Comment by tylercrosse** [comment]
Just a thought - maybe only visualize the recurring events on the longer views?

**Comment by jshawl** [comment]
@amychoi whachu wanna see? google-cal style month view breakdown by days and weeks? or custom view, break down by space usage?

**Comment by amychoi** [comment]
Google-cal style month view by days/weeks... BUT I kinda of love the idea
of monthly space usage for that utilization tab. By event type + event
space respectively.

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874
