### ISSUE TITLE
Refactor coloring of events to better match Amy's current scheme

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/spacey#37]
Currently events receive a color form their event_type
It would cool to have the ability to change the color of individual events independently of their event_type color

**Comment by tylercrosse** [comment]
🐞 fixed with pull #63

**Comment by amychoi** [comment]
@tylercrosse I just went to create a new event and it defaulted the color block as black and will not let me change it to the blue event color. I receive a "We're sorry, but something went wrong." page.

https://gadc.space/events/3775/edit
