### ISSUE TITLE
fix JS validation for check availability on event create/update

### ISSUE THREAD

**Issue by nolds9** [ga-dc/spacey#39]
Currently only checks for overlaps for an event's entire time span, i.e. Monday 8am to Friday 10pm
Instead, we need to check overlap on a specific day...,i.e. Monday 8am to Monday 10pm

**Comment by tylercrosse** [comment]
hot fix was submitted pull #42 , https://github.com/ga-dc/spacey/commit/3206c892bae2696f14bf29c87fe6e2a3305fe4a2, & https://github.com/ga-dc/spacey/commit/3c27e5257e17d70d4d49c49eeae463c885c6b513

**Comment by tylercrosse** [comment]
JS validation before creation

**Comment by bmartinowich** [comment]
@tylercrosse @nolds9 Can we close this?

**Comment by jshawl** [comment]
👍 this is implemented server-side, which is more secure
