### ISSUE TITLE
Support for holidays, exceptions to recurring rules

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/spacey#48]
Currently you can delete an individual event that belongs to a recurring event. However, when that recurring event gets updated it will rebuild all the events that satisfy the recurring rules, this undoes the deletion of individual events. Need some way to prevent this - maybe by updating the recurring rules on delete?

**Comment by tylercrosse** [comment]
Another feature that is needed is validation for holidays - something similar to Tim's tool

**Comment by bmartinowich** [comment]
@tylercrosse Can we incorporate Tim's tool here? or do we need to create something new?
