### ISSUE TITLE
Specific event won't let me update details

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#51]
https://gadc.space/events/2638

This is what pops up when I try to edit Producer + Instructor fields

![screen shot 2016-06-16 at 12 20 38 pm](https://cloud.githubusercontent.com/assets/15385443/16124436/f00db042-33bc-11e6-8ade-6d493dba969e.png)

**Comment by amychoi** [comment]
Happening again with https://gadc.space/events/564

**Comment by jshawl** [comment]
believe this is failing validation on already created event @tylercrosse

**Comment by jshawl** [comment]
fixed!
