### ISSUE TITLE
Specific event color block not reflecting proper time

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#58]
DGM11 is 6:30 PM - 8:30 PM, but it shows it going until 9:30 PM

![screen shot 2016-06-16 at 1 35 33 pm](https://cloud.githubusercontent.com/assets/15385443/16126741/73be5842-33c7-11e6-9ca7-f249fe63de89.png)

![screen shot 2016-06-16 at 1 37 11 pm](https://cloud.githubusercontent.com/assets/15385443/16126743/750de1d6-33c7-11e6-9611-fb9805fedac9.png)

**Comment by jshawl** [comment]
there were two events in one!
