### ISSUE TITLE
Custom color does not update in event

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#72]
This is what comes up when I try to change the custom color and press "Update Event"

![screen shot 2016-06-21 at 11 17 08 am](https://cloud.githubusercontent.com/assets/15385443/16235129/bdabad78-37a1-11e6-879b-40b801ec5340.png)

**Comment by tylercrosse** [comment]
Another 🐞 is that on update some events get colored black

**Comment by jshawl** [comment]
fixed!
