### ISSUE TITLE
Name of event not showing in week view for some events

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#78]
One example

![screen shot 2016-06-28 at 4 28 04 pm](https://cloud.githubusercontent.com/assets/15385443/16431158/55f4986e-3d4d-11e6-9cb5-c43523315934.png)

**Comment by amychoi** [comment]
Another one

![screen shot 2016-06-28 at 4 28 49 pm](https://cloud.githubusercontent.com/assets/15385443/16431173/69e1077c-3d4d-11e6-8443-ce5430ceaa1a.png)

**Comment by jshawl** [comment]
the text is hidden if it can't fit

**Comment by jshawl** [comment]
is this ok? otherwise text is overlapping / unreadable.

**Comment by amychoi** [comment]
Is it possible to show however much text can fit in the block? Even if it's
"Product Managem...", it'll give some idea at a glance what it is

*Amy Choi *| Experience Coordinator
General Assembly http://generalassemb.ly/ | 1133 15th St. NW |
Washington, D.C.
amy.choi@ga.co | 202-823-3874
