### ISSUE TITLE
"Update all" button disappearred for recurring events

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#79]

**Comment by jshawl** [comment]
@tylercrosse want to pair on this at some point today?  relevant: - https://github.com/ga-dc/spacey/commit/d686d89034eada29fa2ee703918ae101df636f14

**Comment by amychoi** [comment]
Status update for this bug? @jshawl

**Comment by jshawl** [comment]
it is the gnarliest of things to implement

**Comment by jshawl** [comment]
Ok I changed my mind - definitely doable. In progress
