### ISSUE TITLE
Specific events won't let me update details

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#84]
Trying to add number of attendees and I'll get the following...

![screen shot 2016-06-30 at 11 42 15 am](https://cloud.githubusercontent.com/assets/15385443/16494550/c1debca6-3eb7-11e6-9b1d-38ec6050005d.png)

This one in particular - nothing happens when I press the "Update Event" button
![screen shot 2016-06-30 at 11 45 10 am](https://cloud.githubusercontent.com/assets/15385443/16494665/1ea0c434-3eb8-11e6-9d65-1b334032d98d.png)

**Comment by amychoi** [comment]
https://gadc.space/events/2638/edit

Trying to update space, producer, and instructor...

![screen shot 2016-06-30 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/15385443/16495648/603ff3b6-3ebc-11e6-8484-6110a9ba7b7c.png)

**Comment by amychoi** [comment]
https://gadc.space/events/3827/edit

Trying to update from 7/18 to 7/19 and it won't let me update this event. It stays on 7/18.

**Comment by jshawl** [comment]
@amychoi I can JS class is in boardroom -Wed, 06 Jul 2016 17:30:00 UTC +00:00 - Sat, 16 Jul 2016 20:00:00 UTC +00:00

that is preventing you from puttin this event in baordroom - what is the right date?

https://gadc.space/events/1708

**Comment by amychoi** [comment]
@jshawl hey, Intro to JavaScript is supposed to be in the Boardroom. What's wrong is the end date is 7/16 when it is supposed to also be 7/6 like the start date.
