### ISSUE TITLE
Specific event won't let me update end date

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#85]
I keep trying to change end date to be 7/6/16 at 8 PM and it keeps repopulating to 7/16/16 at 10 PM

![screen shot 2016-06-30 at 11 55 59 am](https://cloud.githubusercontent.com/assets/15385443/16495034/aa83354e-3eb9-11e6-8abf-1a0ddcb4f9d5.png)

**Comment by amychoi** [comment]
This actually also reveals that an event over continuous days doesn't actually show on a day to day view

**Comment by jshawl** [comment]
can you share the link to this event

**Comment by amychoi** [comment]
@jshawl https://gadc.space/events/1708

**Comment by jshawl** [comment]
fixed
