### ISSUE TITLE
Date does not change in update event

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#88]
I have event - https://gadc.space/events/3818 - originally scheduled for 7/12, that was moved to 7/18. I need to be able to go into the 7/12 event, update the date to 7/18 and press "Update Event" and it moves to 7/18. When I try it right now, the date regenerates to 7/12 and tells me there is a conflict.

**Comment by jshawl** [comment]
fixed https://gadc.space/events/3818
