### ISSUE TITLE
add Tim's tool 

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/spacey#9]

**Comment by jshawl** [comment]
what is tim's tool?

**Comment by bmartinowich** [comment]
@jshawl https://github.com/timfoley/timecheck/blob/master/timecheck.py

**Comment by bmartinowich** [comment]
Basically pulls the dates of the PT/FT courses and holidays for that particular course -- amazing tool that we can use to integrate to automate the events in Spacey!

**Comment by jshawl** [comment]
mentioned in #7
