### ISSUE TITLE
Receiving error message when trying to edit event

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#96]
https://gadc.space/events/4118/edit

When I go to press "edit", I receive "We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

**Comment by amychoi** [comment]
This seems to be happening for any event... I picked random ones and tried to "edit" and I received the same message... @jshawl

**Comment by jshawl** [comment]
i knew i shouldn't have added that cool favicon

**Comment by nolds9** [comment]
Should be fixed @amychoi thanks for the heads up!
