### ISSUE TITLE
Receiving start date validation fail

### ISSUE THREAD

**Issue by amychoi** [ga-dc/spacey#99]
I went to update the start/end date of this event... received this error... went to the conflicting event... and it was the actual event I **just** created.

![screen shot 2016-07-20 at 5 22 48 pm](https://cloud.githubusercontent.com/assets/15385443/17003590/a757d948-4e9e-11e6-9635-ada9490a6800.png)

**Comment by amychoi** [comment]
I went to update the instructors for DSI2 and received the same error...

![screen shot 2016-07-21 at 12 20 44 pm](https://cloud.githubusercontent.com/assets/15385443/17030500/a6805a82-4f3d-11e6-9555-83701eb3279a.png)

**Comment by amychoi** [comment]
Trying to update the color of WDI13 in CR 6 on 11/9 and I receive this error

![screen shot 2016-07-21 at 1 35 47 pm](https://cloud.githubusercontent.com/assets/15385443/17032584/14f1a6d8-4f48-11e6-9e9e-d8542a7f6868.png)

**Comment by nolds9** [comment]
if you edit the color for one day, it will create a new event in-place of the old one
